#!/bin/sh

gcc -O3 -std=c99 mm_ijk_time.c -lpapi -o mm_ijk_time
gcc -O3 -std=c99 mm_ikj_time.c -lpapi -o mm_ikj_time

for matrix in 48 128 512 2048
do
echo "matrix size $matrix x $matrix"
for it in 1 2 3 4 5 6 7 8
do
   ./mm_ikj_time $matrix $matrix"_ikj_time.csv"
   ./mm_ijk_time $matrix $matrix"_ijk_time.csv"
done
done
